config/routes.rb
Rails.application.routes.draw do
  get 'chat/index'
  get 'messages/index'
  devise_for :users
  root "site#index"
  get '/site', to: 'site#index'

  resources :posts do 
    resources :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:index, :create, :destroy, :edit]
  end

  resources :profiles, param: :user_name
  get '/followers/:user_name', to: 'profiles#followers'
  get '/followings/:user_name', to: 'profiles#followings'
  
  resources :friends, only: [:new, :create, :destroy, :index]
  post '/friends/:id', to: 'friends#create'

  resources :chats, only: [:index, :create, :show] do 
    resources :messages 
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  model_name.instance_variable_set(:@route_key, 'profile')
  belongs_to :user
  has_one_attached :photo_of_profile  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    layout "dashboard"
    before_action :set_profile, only: [:show, :edit, :update, :followings]
    before_action :set_user, only: [:show, :followers, :followings]

    def show
        @followers = Friend.where(followed_id: @user.id)
        @followings = @user.followers
        @posts = @user.posts
    end

    def followers
        @followers = Friend.where(followed_id: @user.id)
    end

    def followings
        @followings = @user.followers
    end

    def new
        @profile = Profile.new
    end

    def create
        @profile = Profile.new(profile_params)
        @profile.user_id = current_user.id
        if @profile.save
            redirect_to profile_url, status: :created, notice: 'Profile was created'
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit;end

    def update
        if @profile.update(profile_params)
            redirect_to(profile_path, status: :ok, notice: 'Profile was updated')
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private

    def set_user
       @user = User.find_by(name: params[:user_name])
    end

    def set_profile
        @profile = current_user.profile
    end

    def profile_params
        params.require(:profile).permit(:bio, :photo_of_profile)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, multipart: true, url: profiles_path) do |form|%>
    <div class="flex flex-col gap-3 mb-3">
        <%= form.label :photo_of_profile, 'choose image', class: 'font-bold mb-1' %>
        <%= form.file_field :photo_of_profile, class: 'border border-gray-300 p-2 rounded-lg cursor-pointer'%>
    </div>

    <div class="flex flex-col gap-3 mb-4">
        <%= form.label :bio, 'Your Bio', class: 'font-bold'%>
        <%= form.text_field :bio, class: 'border border-gray-300 p-2 rounded-lg cursor-pointer'%>
    </div>
    <div>
        <%= form.submit nil, class: 'text-white bg-red-600 p-2 rounded-md cursor-pointer'%>
    </div>
<% end %>

app/views/profiles/_post.html.erb
<% posts.each do |post|%>
    <div>
        <%= link_to post_comments_path(post) do %>
            <%= image_tag(url_for(post.image), class: 'w-64 h-64') %>
        <% end %>
    </div>
<% end %>

app/views/profiles/edit.html.erb
<section class="max-w-3xl mx-auto p-4">
    <h1 class="text-2xl font-semibold mb-6">Edit your profile</h1>
    <%= form_with(model: @profile, url:profile_path,local:true, class: "space-y-6") do |form| %>
        <!-- Seção da foto e nome do perfil -->
        <div class="flex justify-between items-center bg-gray-100 p-5 rounded-md shadow-sm">
            <!-- Foto de perfil e detalhes do usuário -->
            <div class="flex items-center gap-4">
                <% if @profile && @profile.photo_of_profile%>
                    <%= image_tag(url_for(@profile.photo_of_profile), class: 'w-32 h-32 rounded-full object-cover') %>
                <% else %>
                     <img class="w-32 h-32 rounded-full" src="https://via.placeholder.com/150" alt="User Avatar">
                <%end%>
                <div>
                    <p class="font-bold text-lg"><%= current_user.name %></p>
                    <p class="text-sm text-gray-500"><%= current_user.name %></p>
                </div>
            </div>
            
            <!-- Campo de upload de nova foto -->
            <%= form.file_field :photo_of_profile, class: 'bg-blue-600 text-white px-4 py-2 rounded cursor-pointer'%> 
        </div>
        <div>
            <%= form.text_field :bio, class: 'w-full bg-gray-100 p-5 rounded-md shadow-sm border-none'%>
        </div>

        <!-- Outros campos podem ser adicionados aqui -->
        <div class="text-right">
            <%= form.submit "Save changes", class: "bg-[#484BFF] hover:bg-[#3437dd] text-white font-semibold py-2 px-4 rounded-md cursor-pointer" %>
        </div>
    <% end %>
</section>

app/views/profiles/followers.html.erb
<%= turbo_frame_tag "followers" do %>
    <section class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
    <div class="bg-white p-6 rounded-lg shadow-lg w-full max-w-lg">
        <h1>All followers</h1>
        <% @followers.each do |user| %>
            <div class="my-5">
                <div class="flex items-center gap-2">
                    <% if user.follower.profile && user.follower.profile.photo_of_profile %>
                        <%= image_tag(url_for(user.follower.profile.photo_of_profile),class: 'w-10 h-10 rounded-full object-cover') %>
                    <% else %>
                        <img class=" w-10 h-10 rounded-full" src="https://via.placeholder.com/150" alt="User Avatar">
                    <% end %>
                    <span><%= user.follower.name %></span>
                </div>
            </div>
        <% end %>
        <%= link_to "Close", posts_path, class: "bg-red-500 text-white py-2 px-4 rounded-lg hover:bg-red-600 transition" %>
    </div>
    </section>
<% end %>

app/views/profiles/followings.html.erb
<%= turbo_frame_tag "followings" do %>
    <section class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
    <div class="bg-white p-6 rounded-lg shadow-lg w-full max-w-lg">
        <h1>All followings</h1>
        <% @followings.each do |user| %>
            <div class="my-5">
                <div class="flex items-center gap-2">
                    <% if user.followed.profile && user.followed.profile.photo_of_profile %>
                        <%= image_tag(url_for(user.followed.profile.photo_of_profile),class: 'w-10 h-10 rounded-full object-cover') %>
                    <% else %>
                        <img class=" w-10 h-10 rounded-full" src="https://via.placeholder.com/150" alt="User Avatar">
                    <% end %>
                    <span><%= user.followed.name %></span>
                    <% if @profile === @user.profile %>
                        <%= link_to "unfollow", friend_path(user.followed.id), data: {turbo_method: :delete}, class: 'text-blue-600 hover:text-blue-800 transition-all underline'%>
                    <% end%>
                    <%=%>
                </div>
            </div>
        <% end %>
        <%= link_to "Close", posts_path, class: "bg-red-500 text-white py-2 px-4 rounded-lg hover:bg-red-600 transition" %>
    </div>
    </section>
<% end %>

app/views/profiles/new.html.erb
<div>
    <h1 class="text-2xl mb-4">Create your profile</h1>
    <%= render 'form', profile: @profile%>
</div>

app/views/profiles/show.html.erb
<div>
    <div class="flex gap-16 mb-12">
            <% if @profile && @profile.photo_of_profile %>
                <%= image_tag(url_for(@user.profile.photo_of_profile ), class: 'w-32 h-32 rounded-full object-cover')%>
            <%else%>
                <img class=" w-32 h-32 rounded-full" src="https://via.placeholder.com/150" alt="User Avatar">
            <% end %>
        <div>
            <div class="flex items-center gap-3 mb-4">
                <span class="text-base font-bold"><%= @user.name%></span>
                <% unless current_user != @user %>
                    <%= link_to "Edit your profile", edit_profile_path, class: 'bg-[#e4e4e4] p-1 rounded-md text-sm'%>
                <% end %>
                <%= link_to "Messasge", "", class: 'bg-[#e4e4e4] p-1 rounded-md text-sm'%>
            </div>
            <div class="flex items-center gap-4 mb-3">
                <p><%= @posts.count%> posts</p>
                <%= link_to "/followers/#{@user.name}", data: {turbo_frame: 'followers'} do %>
                    <p><%= @followers.count%> followers</p>
                <% end %>
                <%= link_to "/followings/#{@user.name}", data: {turbo_frame: 'followings'} do %>
                    <p><%= @followings.count%> following</p>
                <% end %>
            </div>
            <span class="block font-bold mb-3"><%= @user.name%></span>
            <% if @profile && @profile.bio %>
                <p class="max-w-[365px]"><%= @user.profile.bio%></p>
            <%else%>
                <p>No bio</p>
            <% end %>
        </div>
    </div>
    <div class="feed">
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg-grid-cols-4 gap-2">
            <% if @posts.count != 0 %>
                <%= render 'profiles/post', posts: @posts %>
            <% else %>
                <p>No posts</p>
            <% end %>
        </div>
    </div>
</div>

<%= turbo_frame_tag 'followers'%>
<%= turbo_frame_tag 'followings'%>