config/routes.rb
Rails.application.routes.draw do
  get 'chat/index'
  get 'messages/index'
  devise_for :users
  root "site#index"
  get '/site', to: 'site#index'

  resources :posts do 
    resources :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:index, :create, :destroy, :edit]
  end

  resources :profiles, param: :user_name
  get '/followers/:user_name', to: 'profiles#followers'
  get '/followings/:user_name', to: 'profiles#followings'
  
  resources :friends, only: [:new, :create, :destroy, :index]
  post '/friends/:id', to: 'friends#create'

  resources :chats, only: [:index, :create, :show] do 
    resources :messages 
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :image, presence: true

  scope :ordered, -> {order(id: :desc)}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'dashboard'
  before_action :set_post, only: [:destroy]
  before_action :check_profile
  
  def index
    @posts = Post.ordered
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      respond_to do |format|
        format.html {redirect_to(posts_path, status: :created, notice: 'Post was successfuly created')}
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy 
    @post.destroy
    redirect_to posts_path, status: :see_other
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:description, :number_of_likes, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: @post, multipart: true, class: "space-y-4") do |form| %>
        <!-- Campo de upload de imagem -->
        <div class="flex flex-col">
          <%= form.label :image, "Choose image", class: "font-semibold mb-2" %>
          <%= form.file_field :image, class: "border border-gray-300 p-2 rounded-lg" %>
          <% if @post.errors%>
            <p class="text-red-600"><%= @post.errors[:image][0]%></p>
          <% end %>
        </div>
        
        <!-- Campo de descrição -->
        <div class="flex flex-col">
          <%= form.label :description, "Description", class: "font-semibold mb-2" %>
          <%= form.text_field :description, class: "border border-gray-300 p-2 rounded-lg" %>
        </div>
        
        <!-- Botão de submissão -->
        <div class="flex gap-4">
          <%= form.submit "Send", class: "bg-blue-500 text-white font-bold py-2 px-4 rounded-lg hover:bg-blue-600 transition cursor-pointer" %>
          <%= link_to "Cancel",posts_path, class: 'bg-red-500 text-white font-medium py-2 px-4 rounded-lg hover:bg-red-600 transition cursor-pointer'%>
        </div>
      <% end %>

app/views/posts/_post.html.erb
<div class="max-w-md mx-auto bg-white border border-gray-300 rounded-lg shadow-md mb-6 ">
  <!-- Cabeçalho do Post (Nome de usuário e opções) -->
  <div class="flex items-center justify-between p-4">
    <div class="flex items-center space-x-4">
      <%= link_to profile_path(post.user.name), data: {turbo_frame: '_top'} do %>
        <div class="flex items-center gap-2">
          <!-- Avatar e nome do usuário -->
            <% if photo_of_user(post)%>
              <%= image_tag(url_for(photo_of_user(post)), class: 'w-10 h-10 rounded-full object-cover')%>
            <% else %>
              <img class="w-10 h-10 rounded-full" src="https://via.placeholder.com/150" alt="User Avatar">
            <% end %>
            <span class="font-semibold"><%= post.user.name %></span>

          <!-- Separador e tempo do post -->
          <div class="flex items-center gap-1">
            <div class="w-1 h-1 rounded-full bg-[#d9d9d9]"></div>
            <span class="whitespace-nowrap">
              <%= distance_of_time_in_words(post.created_at, Time.current, include_seconds: false) %> 
            </span>
          </div>
        </div>
      <%end%>
    </div>

    <!-- Botão de deletar post -->
    
    <%= link_to '🗑️', post_path(post), data: { turbo_method: :delete }, class: "text-red-500 hover:text-red-700" if post_of_user(post) %>
  </div>

  <!-- Imagem do Post -->
  <div class="w-full h-96 bg-gray-200">
    <%= image_tag(url_for(post.image), class: 'w-full h-full object-cover') if post.image.attached? %>
  </div>

  <!-- Descrição e Botões de Ação -->
  <div class="p-4">
    <!-- Botões de ação (Curtir, Comentar) -->
    <div class="flex items-center justify-between space-x-4 mb-2">
      <div class="flex items-center gap-5">
        <% if already_liked?(post) %>
          <%= button_to post_like_path(post, post.likes.find_by(user_id: current_user.id)), method: :delete do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
              </svg>
          <% end %>
          <% else %>
            <%= button_to post_likes_path(post), method: :post do %>
                <i class="bi bi-heart"></i>
            <% end %>
        <% end %>
        <%= link_to post_comments_path(post),data: {turbo_frame: 'comment_of_post'} do %>
          <i class="bi bi-chat"></i>
        <% end %>
        <i class="bi bi-send"></i>
      </div>
        <i class="bi bi-bookmark"></i>
    </div>
    
    <div>
      <% if post_has_likes(post)%>
        <%= link_to last_user_of_like(post), post_likes_path(post), data: {turbo_frame: 'likes'}%>
        <% else%>
          <%= last_user_of_like(post)%>
      <% end %>
    </div>
    <!-- Descrição do Post -->
    <p class="text-gray-700">
      <% if description_of_post_exists?(post)%>
        <strong><%= post.user.name %> </strong> 
        <%= post.description %></p>
        <% else %> 
          "This post don't has description"
      <% end %>
    </p>
  </div>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts", @post%>
<%= turbo_stream.update "new_post", ""%>

app/views/posts/index.html.erb
<section>
  <%= turbo_frame_tag Post.new%>
  <%= turbo_frame_tag "likes"%>
  <%= turbo_frame_tag "comment_of_post"%>
  <%= turbo_frame_tag "posts" do %>
    <%= render @posts%>
  <% end %>
</section>

app/views/posts/new.html.erb
<%= turbo_frame_tag Post.new do %>
    <section class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
        <div class="bg-white p-6 rounded-lg shadow-lg w-full max-w-lg">
                <h3 class="text-2xl font-bold mb-4 text-center">Criar seu post</h3>
                <%= render 'form', post: @post %>
        </div>
    </section>
<% end %>