config/routes.rb
Rails.application.routes.draw do
  get 'chat/index'
  get 'messages/index'
  devise_for :users
  root "site#index"
  get '/site', to: 'site#index'

  resources :posts do 
    resources :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:index, :create, :destroy, :edit]
  end

  resources :profiles, param: :user_name
  get '/followers/:user_name', to: 'profiles#followers'
  get '/followings/:user_name', to: 'profiles#followings'
  
  resources :friends, only: [:new, :create, :destroy, :index]
  post '/friends/:id', to: 'friends#create'

  resources :chats, only: [:index, :create, :show] do 
    resources :messages 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :sender_user, class_name: "User"
  belongs_to :recipient_user, class_name: "User"
  has_many :messages, dependent: :destroy

  # Normaliza os IDs antes de validar/salvar
  before_validation :normalize_user_ids

  # Garante unicidade dos pares de IDs, independente da ordem
  validates :sender_user_id, uniqueness: { scope: :recipient_user_id, message: "Este chat já existe" }

  scope :between_users, -> (user1,user2) {
    where(
      "(sender_user_id = :user1 AND recipient_user_id = :user2) OR 
       (sender_user_id = :user2 AND recipient_user_id = :user1)",
      user1: user1,
      user2: user2
    )
  }

  private

  # Troca os IDs para garantir sempre a mesma ordem
  def normalize_user_ids
    if sender_user_id > recipient_user_id
      self.sender_user_id, self.recipient_user_id = recipient_user_id, sender_user_id
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :description, presence: true
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :followed, class_name: 'User'
    belongs_to :follower, class_name: 'User'

    validates :follower_id, presence: true
    validates :followed_id, presence: true
    validates :followed_id, uniqueness: {scope: :follower_id, message: "Ja esta na lista de amigos"}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender_user, class_name: "User"
  belongs_to :chat
  
  validates :content, presence: true
  after_create_commit { broadcast_append_to self.chat}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :image, presence: true

  scope :ordered, -> {order(id: :desc)}
end

app/models/profile.rb
class Profile < ApplicationRecord
  model_name.instance_variable_set(:@route_key, 'profile')
  belongs_to :user
  has_one_attached :photo_of_profile  
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :email, uniqueness: true
  validates :name, uniqueness: true
  has_one :profile, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :followers, class_name: "Friend" , foreign_key: "follower_id", dependent: :destroy
  has_many :messages
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  layout "dashboard"
  def index
    @followers = current_user.followers.map(&:followed)
  end

  def show
    @chat_single = Chat.find_by(id: params[:id])
    @followers = current_user.followers.map(&:followed)
    @message = Message.new

    render "index"
  end

  def create
    unless chat_exist?
      @chat = Chat.create!(sender_user_id: current_user.id, recipient_user_id: fetch_recipient.id)
        redirect_to(@chat)
    else
      redirect_to chat_path(seek_chat)
    end
  end

  private
  def fetch_recipient
    User.find(params[:recipient_id])
  end

  def chat_exist?
    Chat.exists?(sender_user_id: current_user.id, recipient_user_id: fetch_recipient.id) || Chat.exists?(sender_user_id: fetch_recipient.id, recipient_user_id: current_user.id)
  end

  def seek_chat
    @chat = Chat.between_users(current_user, fetch_recipient).first
  end
end

#PRECISO PENSAR EM COMO CARREGAR AS MENSAGENS DE UM CHAT ESPECIFICO

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    layout "dashboard"
    before_action :find_post
    before_action :find_like, only: [:destroy]

    def index
        @likes = @post.likes
    end

    def create
        @post.likes.create(user_id: current_user.id)
        @post.number_of_likes += 1
        @post.save
        redirect_to(posts_path)
    end

    def destroy
        @like.destroy if already_liked?
        @post.number_of_likes -= 1
        @post.save
        redirect_to(posts_path)
    end

    private
    def find_post
        @post = Post.find(params[:post_id])
    end

    def find_like
        @like = @post.likes.find(params[:id])
    end

    def already_liked?
        Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def already_liked?(post)
        Like.where(user_id: current_user.id, post: post.id).exists?
    end

    def last_user_of_like(post)
        like = Like.where(post_id: post.id).last
        if like
            name_of_the_last_liked = like.user.name
            "Liked by #{name_of_the_last_liked} and others"
        else
            "be the first to like"
        end
    end

    def post_has_likes(post)
        Like.where(post_id: post).count > 0
    end

    def description_of_post_exists?(post)
        return false if post.description.blank?
        true
    end

    def photo_of_user(post)
        post.user.profile.photo_of_profile
    end

    def post_of_user(post)
        post.user.id === current_user.id
    end
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instadin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instadin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="flex min-h-screen">
      <!-- Sidebar -->
      <aside class="w-64 bg-[#111827] text-white p-4">
        <div class="p-4">
          <%= link_to 'Instadin', posts_path, class: 'text-2xl font-bold text-[#6366f1]' %>
        </div>
        <nav class="mt-5">
          <ul>
            <li class="mb-3">
              <%=link_to posts_path, class: "flex items-center p-3 text-gray-300 hover:bg-gray-700 hover:text-white rounded-lg transition-colors"  do %>
                <i class="bi bi-house"></i>
                <span class="ml-4">Home</span>
              <% end %>
            </li>
            <li class="mb-3">
              <%= link_to chats_path, class:"flex items-center p-3 text-gray-300 hover:bg-gray-700 hover:text-white rounded-lg transition-colors" do%>
                <i class="bi bi-chat"></i>
                <span class="ml-4">Chat</span>
              <% end %>
            </li>
            <li class="mb-3">
              <%= link_to new_friend_path ,class:"flex items-center p-3 text-gray-300 hover:bg-gray-700 hover:text-white rounded-lg transition-colors" do%>
                <i class="bi bi-people"></i>
                <span class="ml-4">Friends</span>
              <% end %>
            </li>
              <li class="mb-3">
                <%= link_to new_post_path, class: "flex items-center p-3 text-gray-300 hover:bg-gray-700 hover:text-white rounded-lg transition-colors",data: {turbo_frame: 'new_post'} do %>
                  <i class="bi bi-plus-circle"></i>
                  <span class="ml-4">Post</span>
                <% end %>
              </li>
          </ul>
        </nav>
        <div class="bg-white p-[0.4px] mb-4"></div>
        <div>
          <h3>Your groups</h3>
          <nav class="mt-5">
          <ul>
            <li class="mb-3">
              <a href="#" class="flex items-center p-3 text-gray-300 hover:bg-gray-700 hover:text-white rounded-lg transition-colors">
                <i class="bi bi-1-circle"></i>
                <span class="ml-4">Melhore viagens para europa...</span>
              </a>
            </li>
          </ul>
        </nav>
        </div>
      </aside>

      <!-- Main Content -->
      <div class="flex-1 flex flex-col">
        <!-- Header -->
        <header class="flex items-center justify-between p-4 bg-white shadow-md">
          <!-- Search Bar -->
          <div class="flex items-center w-full max-w-md gap-2">
            <input type="text" placeholder="Search..." class="w-full px-4 py-2 bg-gray-100 border rounded-lg outline-none focus:ring-2 focus:ring-[#6366F1">
            <button class="text-white p-2 rounded-md bg-[#6366F1] hover:bg-[#484bff]">Search</button>
          </div>

          <!-- Icons -->
          <div class="flex items-center space-x-4">
            <!-- Notification Icon -->
            <button class="relative text-gray-600 hover:text-gray-900 focus:outline-none">
              <i class="bi bi-bell text-2xl"></i>
              <!-- Notification Badge -->
              <span class="absolute top-0 right-0 inline-block w-2 h-2 bg-red-500 rounded-full"></span>
            </button>

            <div class="bg-[#d9d9d9] p-[0.4px] h-6"></div>

            <!-- User Avatar -->
            <div data-controller="modal" data-action="click->modal#handleModal" class="flex items-center gap-2 cursor-pointer">
              <div class="w-10 h-10 rounded-full overflow-hidden">
                <% if current_user.profile &&  current_user.profile.photo_of_profile %>
                  <%= image_tag(url_for(current_user.profile.photo_of_profile), class: 'object-cover w-full h-full') %>
                <%else%>
                    <img class=" w-32 h-32 rounded-full" src="https://via.placeholder.com/150" alt="User Avatar">
                <% end %>
              </div>
              <span><%= current_user.name%> <i class="bi bi-caret-down"></i></span>
            </div>
            <!-- MODAL HERE -->
            <div class="modal fixed flex top-16  justify-center bg-white z-50 w-32 rounded-md border border-opacity-20 border-black p-2 transition-all shadow-md hidden">
                <div class="flex flex-col">
                   <button data-controller="modal" data-action="click->modal#handleModal" class="absolute top-[-4px] right-2 text-gray-500 hover:text-gray-700">&times;</button>
                  <%= link_to "Your profile", profile_path(current_user.name) %>
                  <%= link_to "Create groupp", posts_path %>
                  <%= link_to "exit", destroy_user_session_path, class: 'text-red-600',data: {turbo_method: :delete,  turbo_confirm: 'Are sure?'} %>
                </div>
            </div>
          </div>
        </header>

        <!-- Main Section -->
        <main class="flex-1 p-8">
          <%= yield%>
        </main>
      </div>
    </div>
  </body>
</html>